spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5423/metallic_db
spring.datasource.username=metallic_admin
spring.datasource.password=SteelShield2026!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8082
